export const routes = {
  home: "/",
  browseHome: "/browse-home",
  homeDetails: "/home-details",
  homeDetailsFor: (slug: string) =>
    `/home-details?slug=${encodeURIComponent(slug)}`,
  services: "/services",
  serviceProviderDetails: (slug: string) => `/services/${slug}`,
  about: "/about",
  contactUs: "/contact-us",
  faq: "/faq",
  signIn: "/signin",
  adminSignIn: "/admin/signin",
  verifyEmail: "/verify-email",
  pendingApproval: "/pending-approval",
  accountRejected: "/account-rejected",
  accountSuspended: "/account-suspended",
  accountDisabled: "/account-disabled",
  signUpTenant: "/signup/tenant",
  signUpTenantForm: "/signup/tenant/tenant-form",
  signUpTenantVerifyIdentity: "/signup/tenant/verify-identity",
  signUpTenantDetails: "/signup/tenant/tenant-details",
  signUpOwner: "/signup/owner",
  signUpOwnerForm: "/signup/owner/owner-form",
  signUpOwnerVerifyIdentity: "/signup/owner/verify-identity",
  signUpOwnerDetails: "/signup/owner/owner-details",
  signUpServiceProvider: "/signup/service-provider",
  signUpServiceProviderForm: "/signup/service-provider/service-provider-form",
  signUpServiceProviderVerifyIdentity: "/signup/service-provider/verify-identity",
  signUpServiceProviderDetails: "/signup/service-provider/service-provider-details",
  adminOverview: "/admin/overview",
  adminUserManagement: "/admin/user-management",
  adminListingVerification: "/admin/listing-verification",
  adminProviderVerification: "/admin/provider-verification",
  adminReportsAnalytics: "/admin/reports-&-analytics",
  adminSupport: "/admin/support",
  adminSiteSettings: "/admin/site-settings",
  tenantOverview: "/tenant/overview",
  tenantMyBookings: "/tenant/my-bookings",
  tenantSavedHomes: "/tenant/saved-homes",
  tenantServiceRequests: "/tenant/service-requests",
  tenantMessages: "/tenant/messages",
  tenantProfile: "/tenant/profile",
  ownerOverview: "/owner/overview",
  ownerMyListings: "/owner/my-listings",
  ownerAddNewListing: "/owner/add-new-listing",
  ownerBookingRequests: "/owner/booking-requests",
  ownerEarnings: "/owner/earnings",
  ownerMessages: "/owner/messages",
  ownerProfile: "/owner/profile",
  serviceProviderOverview: "/service-provider/overview",
  serviceProviderJobRequests: "/service-provider/job-requests",
  serviceProviderMySchedule: "/service-provider/my-schedule",
  serviceProviderServiceProfile: "/service-provider/service-profile",
  serviceProviderEarnings: "/service-provider/earnings",
  serviceProviderMessages: "/service-provider/messages",
  serviceProviderReviews: "/service-provider/reviews",
} as const;
